### ISSUE TITLE
ValueError: Too many packets in payload

### ISSUE THREAD

**Issue by ftsell** [TheNerdful8/Lecture2Gether#77]
[Sentry](https://sentry2.mafiasi.de/organizations/sentry/issues/50/?environment=production&project=3) - Please ask Timon or me for further details.

```
ValueError: Too many packets in payload
  File "engineio/server.py", line 396, in handle_request
    socket.handle_post_request(environ)
  File "engineio/socket.py", line 128, in handle_post_request
    p = payload.Payload(encoded_payload=body)
  File "engineio/payload.py", line 15, in __init__
    self.decode(encoded_payload)
  File "engineio/payload.py", line 76, in decode
    raise ValueError('Too many packets in payload')
```

**Comment by Flova** [comment]
https://github.com/miguelgrinberg/python-engineio/issues/142

Maybe this is related.

**Comment by Flova** [comment]
Thx for @timonegk for the additional info.

The error seems to be not relevant in a realistic use-case because socket.io throws an error if more than 50 state updates are sent to the user via one http request as described in the linked issue. This happens due to security reasons. 
In the described case ~120 updates are packed in one request, this is only possible if the user triggers many state updates in a short time (hundreds per second). The user could e.g. fall asleep on the spacebar or something like that.

This is only reasoned form the sentry reporting and could not be reproduced in any way.
